"""Tests for the ffmpeg wrapper.

Split deliberately into two halves:

* Everything about *filter graphs* is pure and runs in microseconds, because
  those are value objects. This is the payoff for not building strings inline -
  the logic that decides what gets erased is testable without media.
* Everything about *running ffmpeg* is an integration test against a clip
  generated by ffmpeg itself (see conftest.py), so the suite carries no binary
  fixtures and still proves the argument lists we build are ones ffmpeg will
  actually accept.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.infra.ffmpeg import (
    Ffmpeg,
    FFmpegError,
    FFmpegTimeoutError,
    Filter,
    FilterChain,
    FilterGraph,
    between,
    escape_value,
    parse_probe,
)

# =============================================================================
#  Pure: filter graph construction
# =============================================================================


class TestFilterRendering:
    def test_filter_without_params_is_just_its_name(self) -> None:
        assert Filter("null").render() == "null"

    def test_params_are_colon_separated(self) -> None:
        rendered = Filter("delogo", {"x": 10, "y": 20, "w": 100, "h": 40}).render()
        assert rendered == "delogo=x=10:y=20:w=100:h=40"

    def test_floats_avoid_scientific_notation(self) -> None:
        """`str(1e-05)` is "1e-05", which ffmpeg's expression parser rejects."""
        assert Filter("f", {"v": 0.00001}).render() == "f=v=0"
        assert Filter("f", {"v": 1.5}).render() == "f=v=1.5"
        assert Filter("f", {"v": 2.0}).render() == "f=v=2"

    def test_booleans_render_as_flags_not_python_words(self) -> None:
        assert Filter("f", {"on": True, "off": False}).render() == "f=on=1:off=0"


class TestEscaping:
    @pytest.mark.parametrize(
        ("raw", "escaped"),
        [
            ("between(t,1,2)", "between(t\\,1\\,2)"),
            ("a:b", "a\\:b"),
            ("a;b", "a\\;b"),
            ("[in]", "\\[in\\]"),
            ("it's", "it\\'s"),
            ("back\\slash", "back\\\\slash"),
        ],
    )
    def test_structural_characters_are_escaped(self, raw: str, escaped: str) -> None:
        assert escape_value(raw) == escaped

    def test_escaping_is_single_pass(self) -> None:
        """A backslash already in the value must be escaped once, not twice -
        which is why this uses `str.translate` rather than chained `.replace()`."""
        assert escape_value("a\\,b") == "a\\\\\\,b"

    def test_plain_values_are_untouched(self) -> None:
        assert escape_value("min(ih,720)") == "min(ih\\,720)"
        assert escape_value("veryfast") == "veryfast"


class TestTimeGating:
    def test_between_builds_a_timeline_expression(self) -> None:
        assert between(1.5, 3.25) == "between(t,1.500,3.250)"

    def test_enable_is_escaped_when_rendered(self) -> None:
        """The commas inside the expression must not read as filter separators -
        if they did, ffmpeg would see three filters instead of one."""
        rendered = Filter("delogo", {"x": 1}, enable=between(0.0, 2.0)).render()
        assert rendered == "delogo=x=1:enable=between(t\\,0.000\\,2.000)"


class TestFilterGraph:
    def test_empty_graph_produces_no_arguments(self) -> None:
        """A video with no detected overlays must be passed through, not run
        through an empty graph - ffmpeg rejects one."""
        assert FilterGraph().is_empty
        assert FilterGraph().to_args() == []
        assert FilterGraph([FilterChain([])]).to_args() == []

    def test_single_unlabelled_chain_uses_vf(self) -> None:
        graph = FilterGraph([FilterChain([Filter("scale", {"w": -2, "h": 720})])])
        assert graph.is_simple
        assert graph.to_args() == ["-vf", "scale=w=-2:h=720"]

    def test_labelled_chain_uses_filter_complex(self) -> None:
        graph = FilterGraph(
            [
                FilterChain(
                    [Filter("overlay", {"x": 0, "y": 0})], inputs=["0:v", "1:v"], outputs=["out"]
                )
            ]
        )
        assert not graph.is_simple
        flag, value = graph.to_args()
        assert flag == "-filter_complex"
        assert value == "[0:v][1:v]overlay=x=0:y=0[out]"

    def test_multiple_chains_are_semicolon_separated(self) -> None:
        graph = FilterGraph(
            [
                FilterChain([Filter("scale", {"w": -2, "h": 720})], inputs=["0:v"], outputs=["v0"]),
                FilterChain([Filter("null")], inputs=["v0"], outputs=["out"]),
            ]
        )
        assert graph.render() == "[0:v]scale=w=-2:h=720[v0];[v0]null[out]"

    def test_overlay_removal_chain_matches_the_intended_shape(self) -> None:
        """The shape step 8 will produce: one time-gated `delogo` per detected
        overlay, chained into a single pass over the video."""
        graph = FilterGraph(
            [
                FilterChain(
                    [
                        Filter(
                            "delogo",
                            {"x": 10, "y": 20, "w": 100, "h": 40},
                            enable=between(0.0, 2.5),
                        ),
                        Filter(
                            "delogo",
                            {"x": 5, "y": 600, "w": 300, "h": 80},
                            enable=between(3.0, 7.0),
                        ),
                    ]
                )
            ]
        )
        assert graph.to_args() == [
            "-vf",
            "delogo=x=10:y=20:w=100:h=40:enable=between(t\\,0.000\\,2.500),"
            "delogo=x=5:y=600:w=300:h=80:enable=between(t\\,3.000\\,7.000)",
        ]


# =============================================================================
#  Pure: ffprobe payload parsing
# =============================================================================


def probe_payload(**video_overrides: object) -> dict[str, object]:
    video = {
        "codec_type": "video",
        "codec_name": "h264",
        "width": 1080,
        "height": 1920,
        "avg_frame_rate": "30000/1001",
    }
    video.update(video_overrides)
    return {
        "streams": [video, {"codec_type": "audio", "codec_name": "aac"}],
        "format": {"duration": "12.5"},
    }


class TestProbeParsing:
    def test_reads_the_fields_the_pipeline_needs(self) -> None:
        info = parse_probe(Path("clip.mp4"), probe_payload())
        assert (info.width, info.height) == (1080, 1920)
        assert info.duration_s == 12.5
        assert info.video_codec == "h264"
        assert info.has_audio is True
        assert info.fps == pytest.approx(29.97, abs=0.01)

    def test_ntsc_frame_rate_is_a_rational_not_a_decimal(self) -> None:
        assert parse_probe(Path("c.mp4"), probe_payload()).fps != 30.0

    def test_variable_frame_rate_reports_zero_rather_than_dividing_by_zero(self) -> None:
        info = parse_probe(Path("c.mp4"), probe_payload(avg_frame_rate="0/0"))
        assert info.fps == 0.0

    def test_missing_container_duration_falls_back_to_the_stream(self) -> None:
        payload = probe_payload(duration="8.0")
        payload["format"] = {}
        assert parse_probe(Path("c.mp4"), payload).duration_s == 8.0

    def test_missing_video_stream_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="no video stream"):
            parse_probe(Path("audio.m4a"), {"streams": [{"codec_type": "audio"}], "format": {}})

    def test_audio_absence_is_detected(self) -> None:
        payload = probe_payload()
        payload["streams"] = [payload["streams"][0]]  # type: ignore[index]
        assert parse_probe(Path("c.mp4"), payload).has_audio is False


class TestRotation:
    """Phone-shot vertical video stores landscape pixels plus a rotation. Getting
    this wrong would mean every bounding box is expressed against the wrong
    dimensions."""

    def test_display_matrix_rotation_swaps_display_dimensions(self) -> None:
        payload = probe_payload(width=1920, height=1080, side_data_list=[{"rotation": -90}])
        info = parse_probe(Path("c.mp4"), payload)
        assert (info.width, info.height) == (1920, 1080)  # as stored
        assert (info.display_width, info.display_height) == (1080, 1920)  # as seen
        assert info.is_vertical

    def test_negative_and_legacy_rotations_agree(self) -> None:
        """A display matrix reports -90 where the old tag reported 270."""
        matrix = parse_probe(Path("c.mp4"), probe_payload(side_data_list=[{"rotation": -90}]))
        legacy = parse_probe(Path("c.mp4"), probe_payload(tags={"rotate": "270"}))
        assert matrix.rotation == legacy.rotation == 270

    def test_180_rotation_does_not_swap_dimensions(self) -> None:
        info = parse_probe(
            Path("c.mp4"),
            probe_payload(width=1920, height=1080, side_data_list=[{"rotation": 180}]),
        )
        assert (info.display_width, info.display_height) == (1920, 1080)

    def test_no_rotation_metadata_is_zero(self) -> None:
        assert parse_probe(Path("c.mp4"), probe_payload()).rotation == 0


# =============================================================================
#  Integration: a real ffmpeg process
# =============================================================================


class TestAgainstRealFfmpeg:
    async def test_probe_reads_a_real_file(self, ffmpeg: Ffmpeg, sample_video: Path) -> None:
        info = await ffmpeg.probe(sample_video)
        assert (info.width, info.height) == (320, 240)
        assert info.duration_s == pytest.approx(2.0, abs=0.2)
        assert info.fps == pytest.approx(30.0, abs=0.1)
        assert info.video_codec == "h264"
        assert info.has_audio

    async def test_a_rendered_filter_graph_is_accepted_by_ffmpeg(
        self, ffmpeg: Ffmpeg, sample_video: Path, tmp_path: Path
    ) -> None:
        """The one test that proves our escaping is right.

        The `enable` expression contains commas; if they were not escaped ffmpeg
        would parse them as filter separators and fail. Asserting on the string
        alone could not catch a rule we had simply got wrong.
        """
        out = tmp_path / "masked.mp4"
        graph = FilterGraph(
            [
                FilterChain(
                    [
                        Filter(
                            "delogo", {"x": 10, "y": 10, "w": 80, "h": 40}, enable=between(0.5, 1.5)
                        )
                    ]
                )
            ]
        )
        await ffmpeg.run(["-i", str(sample_video), *graph.to_args(), "-c:a", "copy", str(out)])

        assert out.exists()
        assert (await ffmpeg.probe(out)).duration_s == pytest.approx(2.0, abs=0.2)

    async def test_failure_carries_the_command_and_stderr(self, ffmpeg: Ffmpeg) -> None:
        with pytest.raises(FFmpegError) as excinfo:
            await ffmpeg.run(["-i", "does-not-exist.mp4", "out.mp4"])

        error = excinfo.value
        assert error.returncode != 0
        assert "does-not-exist.mp4" in error.command
        assert error.stderr  # the reason, not just the exit code

    async def test_timeout_kills_the_process(self, tmp_path: Path) -> None:
        """A runaway encode must not outlive its await and keep a core busy."""
        impatient = Ffmpeg(default_timeout_s=0.05)
        with pytest.raises(FFmpegTimeoutError):
            await impatient.run(
                [
                    "-f",
                    "lavfi",
                    "-i",
                    "testsrc2=size=1920x1080:rate=60:duration=60",
                    "-c:v",
                    "libx264",
                    "-preset",
                    "veryslow",
                    str(tmp_path / "slow.mp4"),
                ]
            )
